[package]
name = "rust-payjoin-rn"
version = "0.1.4"
edition = "2024"

[dependencies]
payjoin = "0.24.0"
url = "2.5.0"       
bitcoin = "0.32.6"
uniffi = "0.29.3"

[[bin]]
name = "rust-payjoin-rn"
path = "src/lib.rs" # Ensure this file exists