[package]
name = "rus-payjoin-rn"
version = "0.1.2"
edition = "2021"

[dependencies]
payjoin = "0.23.0"
url = "2.5.0"       
bitcoin = "0.32.6"

[[bin]]
name = "rus-payjoin-rn"
path = "src/lib.rs" # Ensure this file exists
